apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
   - name: myvolumes-container
     image: tomcat:8.5
     volumeMounts:
      - name: storage-drive
        mountPath: "/usr/local/tomcat/logs"
  volumes:
   - name: storage-drive
     persistentVolumeClaim:
       claimName: my-pvc

